theme: jekyll-theme-minimal
title: "AdA Project"
description: "Research group “Audio-visual rhetorics of affect” - FU Berlin + HPI Potsdam"

navigation:
  - title: "Home"
    url: /    
  - title: "About the Project"
    url: /about    
  - title: "AdA Ontology"
    url: /ontology    

markdown: kramdown

author:
  name: Henning Agt-Rickauer
