theme: jekyll-theme-minimal
title: "AdA Project"
description: "Research group “Audio-visual rhetorics of affect” (Affektrhetoriken des Audiovisuellen)"

navigation:
  - title: "Home"
    url: /    
  - title: "About the Project"
    url: /about    
  - title: "AdA Ontology"
    url: /ontology    
