theme: jekyll-theme-minimal
title: "AdA Project"
description: "Research group “Audio-visual rhetorics of affect” - FU Berlin + HPI Potsdam"

navigation:
  - title: "Home"
    url: /    
  - title: "About the Project"
    url: /about    
  - title: "AdA Ontology"
    url: /ontology    
    subitems: 
      - title: "- Purpose"
        url: /ontology/#Purpose    
      - title: "- Structure"
        url: /ontology/#Structure    
      - title: "- Content"
        url: /ontology/#Content    
  - title: "Annotations"
    url: /annotations    

markdown: kramdown

author:
  name: Henning Agt-Rickauer
